name: Attach Integration ZIP to Release

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      INTEGRATION: chores4kids
    steps:
      - uses: actions/checkout@v4

      - name: Verify integration exists
        run: test -f custom_components/${{ env.INTEGRATION }}/manifest.json

      - name: Extract version from tag
        id: ver
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Update manifest.json with release version
        run: |
          jq --arg v "${{ steps.ver.outputs.version }}" '.version=$v' \
            custom_components/${{ env.INTEGRATION }}/manifest.json \
            > manifest.tmp
          mv manifest.tmp custom_components/${{ env.INTEGRATION }}/manifest.json

      # (valgfrit) commit selve versionsbumpet til repoet
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     add: custom_components/${{ env.INTEGRATION }}/manifest.json
      #     message: "chore: bump manifest to ${{ steps.ver.outputs.version }}"

      - name: Build HACS-compatible ZIP
        run: |
          mkdir -p dist
          zip -r "dist/${{ env.INTEGRATION }}-${{ steps.ver.outputs.version }}.zip" \
            "custom_components/${{ env.INTEGRATION }}" \
            -x "**/__pycache__/*" "**/*.pyc" ".DS_Store" ".git/*"

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*.zip
