name: Attach Integration ZIP to Release
on:
  release:
    types: [published, prereleased]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to attach assets to (e.g. v1.0.0)'
        required: false

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      INTEGRATION: chores4kids
      HACS_ZIP: chores4kids.zip
    steps:
      - uses: actions/checkout@v4

      - name: Determine tag
        id: tag
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Extract version from tag
        id: ver
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"

      - name: Bump manifest.json version
        run: |
          jq --arg v "${{ steps.ver.outputs.version }}" '.version=$v' \
            custom_components/${{ env.INTEGRATION }}/manifest.json > m.tmp
          mv m.tmp custom_components/${{ env.INTEGRATION }}/manifest.json

      - name: Build ZIPs (HACS + versioned)
        run: |
          mkdir -p dist
          zip -r "dist/${{ env.HACS_ZIP }}" "custom_components/${{ env.INTEGRATION }}" \
            -x "**/__pycache__/*" "**/*.pyc" ".DS_Store" ".git/*"
          zip -r "dist/${{ env.INTEGRATION }}-${{ steps.ver.outputs.version }}.zip" \
            "custom_components/${{ env.INTEGRATION }}" \
            -x "**/__pycache__/*" "**/*.pyc" ".DS_Store" ".git/*"

      - name: Sanity check ZIP layout
        run: |
          unzip -l dist/${{ env.HACS_ZIP }} | awk '{print $4}' \
          | grep -qx "custom_components/${{ env.INTEGRATION }}/manifest.json" \
          || (echo "::error ::ZIP must contain custom_components/${{ env.INTEGRATION }}/manifest.json at root"; exit 1)

      - name: Upload ZIP assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            dist/${{ env.HACS_ZIP }}
            dist/${{ env.INTEGRATION }}-${{ steps.ver.outputs.version }}.zip
